### ISSUE TITLE
Wayland support

### ISSUE THREAD

**Issue by faulesocke** [carnager/rofi-pass#209]
Apparently #151 was closed because the OP lost interest in it. However, I am currently trying to use rofi-pass on wayland (sway) and it almost works: rofi renders fine but no password is typed. In the console I see this:

```
/bin/rofi-pass: line 162: xset: command not found
/bin/rofi-pass: line 163: xset: command not found
/bin/rofi-pass: line 181: xset: command not found
```

**Comment by carnager** [comment]
There is simply nothing we can do: https://github.com/jordansissel/xdotool/issues/282

**Comment by digital-mystik** [comment]
> There is simply nothing we can do: [jordansissel/xdotool#282](https://github.com/jordansissel/xdotool/issues/282)
> There is the ydotool, which in theory works, but it a) requires root access to some device node and b) is not complete because I didn't feel like working on it because of a)

I am currently using the ydotool branch which does work, but it has to be added to the input group (I agree that root access is a bit scary). In regard to the ydotool branch, I noticed that the AUR package has xclip as a dependency; so it still needs xwayland to function? 

I was also wondering if it would be possible to implement wtype instead of ydotool/xclip. I use another package (rofi-rbw) that is able to autofill in wayland without xclip/xdotool using wtype. Maybe that is the best option for wayland users?

Apologies if I am totally wrong about that since I don't know much haha.

**Comment by ayushnix** [comment]
Hi @faulesocke, not sure if you're still looking for a solution but you may wanna try [tessen](https://github.com/ayushnix/tessen). Kind of a shameless plug but rofi-pass not working was one of the deal breakers for me as well when I switched to sway.

**Comment by carnager** [comment]
done in https://github.com/carnager/rofi-pass/commit/fa16c0211d898d337e76397d22de4f92e2405ede
