### ISSUE TITLE
rofi deprecating -dump-xresources

### ISSUE THREAD

**Issue by jordan-schneider** [carnager/rofi-pass#223]
Rofi has deprocated `rofi -dump-xresources`, which is used in this script. This caused me to see a confusing error message. Commenting out the "set help color" section fixes the issue for me, but I don't know how to replicate that functionality.

**Comment by ghost91-** [comment]
I don't think it's easy to replicate the functionality, since rofi has switched to using themes, which can style the different "components" with a CSS-like syntax, which makes it easy since you would need to resolve the variables to figure out the actual color used for the component where the help text is being displayed. I would probably just remove the `help_color` functionality all together. Alternatively, you could set the `HELP` variables to only include the `color='$help_color'` property only conditionally:
```bash
	if [[ $help_color == "" ]]; then
	    HELP_COLOR_ATTRIBUTE=""
	else
	    HELP_COLOR_ATTRIBUTE=" color='$help_color'"
        fi
        HELP="<span${HELP_COLOR_ATTRIBUTE}>Selected entry: ${selected_password}</span>"
```
